### ISSUE TITLE
关于把mosdns作为路由器最上游？

### ISSUE THREAD

**Issue by GD2021** [Plutonium141/mosdns-config#2]
您好，我再旁路由上配置mosdns，怎么把他作为主路由的最上游呢？

**Comment by Plutonium141** [comment]
去找主路由的dns设置 不同系统的dns设置位置也不一样，所以我也没法教你

**Comment by GD2021** [comment]
![image](https://user-images.githubusercontent.com/81171294/204264037-d51b350c-bd91-4da4-a8b8-625caf79102c.png)
是不是添加在这里，写上192.168.2.2旁路由的网关

**Comment by Plutonium141** [comment]
写在dhcp里也可以，这样客户端会直接去旁路由解析

**Comment by GD2021** [comment]
感谢！！！

**Comment by GD2021** [comment]
![image](https://user-images.githubusercontent.com/81171294/204844867-dbcb19c0-1364-4578-9408-95218600e109.png)
![image](https://user-images.githubusercontent.com/81171294/204844975-0ba66c3a-dc35-4134-8cb9-b490e9a346f0.png)
![image](https://user-images.githubusercontent.com/81171294/204845031-8d907b01-6ac5-4dbd-997b-2045fdafe733.png)
![image](https://user-images.githubusercontent.com/81171294/204845085-46e91ab8-da20-41a8-b19c-1e7670de158f.png)
![image](https://user-images.githubusercontent.com/81171294/204845193-5a4a33e2-e625-4317-8d9c-904558c88b89.png)
老哥，请教一下，为什么这里不是5301的端口，而是显示clash的监听端口？这样mosdns还是最上游吗？

**Comment by Plutonium141** [comment]
> ![image](https://user-images.githubusercontent.com/81171294/204844867-dbcb19c0-1364-4578-9408-95218600e109.png) ![image](https://user-images.githubusercontent.com/81171294/204844975-0ba66c3a-dc35-4134-8cb9-b490e9a346f0.png) ![image](https://user-images.githubusercontent.com/81171294/204845031-8d907b01-6ac5-4dbd-997b-2045fdafe733.png) ![image](https://user-images.githubusercontent.com/81171294/204845085-46e91ab8-da20-41a8-b19c-1e7670de158f.png) ![image](https://user-images.githubusercontent.com/81171294/204845193-5a4a33e2-e625-4317-8d9c-904558c88b89.png) 老哥，请教一下，为什么这里不是5301的端口，而是显示clash的监听端口？这样mosdns还是最上游吗？

这里是clash的端口是因为你开启了clash的本地dns劫持 因为你在clash里配置了上游dns为mos，所以mosdns已经是最上游了，而mosdns也不需要勾选dns转发
另外clash里只配置一个nameserver即可，fallback可以不用配置，因为这是唯一的上游

**Comment by GD2021** [comment]
收到🫡 明白 感谢🙏

**Comment by GD2021** [comment]
大佬什么时候更新配置？

**Comment by Plutonium141** [comment]
> 大佬什么时候更新配置？

以后也许会找时间更新一下
